# [1、PyTorch介绍与张量的创建](https://www.bilibili.com/video/BV1ov411M7xL?spm_id_from=333.788.videopod.sections&vd_source=cdd897fffb54b70b076681c3c4e4d45d)
[Tensor](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html) 是多维数组，矩阵是二维
pytorch使用Tensor来对模型处理、计算
Tensor和numpy数组很像，但张量可以在GPU中运行，此外张量和np数组可以共享同一块内存，只要你是原地操作。
张量支持自动微分

In [2]:
import torch
import numpy as np

## 创建张量的方法

### 从源数据中创建

In [6]:
# 1. 直接从 数组创建
data = [[1,2], [3,4]]
x = torch.Tensor(data)
print(f"{type(data), type(x), x.dtype}")
print(x)

(<class 'list'>, <class 'torch.Tensor'>, torch.float32)
tensor([[1., 2.],
        [3., 4.]])


In [15]:
np_data = np.array(data)
# 使用 torch.from_numpy()：共享内存。
# 使用 torch.tensor()：不共享内存（会创建副本）。
# 使用 torch.as_tensor()：可能共享内存，如果dtype和设备兼容且NumPy数组是连续的，则共享；否则会创建副本。

x = torch.from_numpy(np_data)
# y = torch.from_numpy(np_data)
print(f"{np_data}\n{x}")
# 现在修改 np 中的元素，看看x是否一样
np_data[0,0] *= -1
print(f"{np_data}\n{x}")

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])
[[-1  2]
 [ 3  4]]
tensor([[-1,  2],
        [ 3,  4]])


### 指定分布

In [16]:
x = torch.zeros((2,3))
print(x)
x = torch.ones(x.shape)
print(x)
x = torch.rand_like(x)
print(x)
x = torch.empty(x.shape) # 不初始化数据
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9267, 0.6991, 0.3671],
        [0.1024, 0.4135, 0.1172]])
tensor([[5.5216e-05, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4580e-19]])


In [42]:
torch.linspace(start=0, end=1, steps=11) # 一共11个，线性均匀分布
# 包含头尾

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

In [40]:
torch.logspace(start=0, end=2, steps=3)

tensor([  1.,  10., 100.])

In [36]:
# 对角线全为1
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [32]:
# arange 不包含end
torch.arange(start=0, end=10, step=1)
# range过时了

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
torch.full((2,2), fill_value=10)

tensor([[0, 0],
        [0, 0]])

## Tensor 基本操作

### 判断

In [31]:
# torch.is_tensor 是不是张量
x = torch.empty(2,3)
y = np.empty_like(x)
print("是不是张量：", torch.is_tensor(x), torch.is_tensor(y))

x = torch.Tensor([1])
y = torch.Tensor([False])
print("是不是非零：", torch.is_nonzero(x), torch.is_nonzero(y))


x = torch.Tensor([1,2,3])
y = torch.complex(torch.zeros(1,2), torch.ones(1,2))
print("是不是非零：", torch.is_complex(x), torch.is_complex(y))

是不是张量： True False
是不是非零： True False
是不是非零： False True


### 存储

In [19]:
x = torch.empty((2,3))
print(x.device)
if torch.cuda.is_available():
    x = x.to('cuda')
    print(x.device)

cpu
cuda:0


In [45]:
# cat操作
a = torch.ones((2,2))
b = torch.ones((2,2)) * 2
print(torch.cat([a,b], dim=0)) # 对行扩充 --> 4 行
print(torch.cat([a,b], dim=1)) # 对列扩充 --> 4 列

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1., 2., 2.],
        [1., 1., 2., 2.]])


### 计算

见：[2、PyTorch张量的运算API（上）](2、PyTorch张量的运算API（上）.ipynb)

In [18]:
x = torch.ones((2,1))
x

tensor([[1.],
        [1.]])