# [2、PyTorch张量的运算API（上）](https://www.bilibili.com/video/BV1wQ4y1q7Bm?spm_id_from=333.788.player.switch&vd_source=cdd897fffb54b70b076681c3c4e4d45d)

In [1]:
import torch

In [2]:
b = torch.rand(3,2)
b



tensor([[0.8978, 0.1323],
        [0.7349, 0.8007],
        [0.4459, 0.7735]])

In [3]:
# 按照行分割成2个张量
torch.chunk(b, chunks=2, dim=0)



(tensor([[0.8978, 0.1323],
         [0.7349, 0.8007]]),
 tensor([[0.4459, 0.7735]]))

In [4]:
# 按照行分割成2个张量
torch.chunk(b, chunks=2, dim=1)

(tensor([[0.8978],
         [0.7349],
         [0.4459]]),
 tensor([[0.1323],
         [0.8007],
         [0.7735]]))

In [5]:
t = torch.tensor([[1, 2], [3, 4]])
print(t)
# dim=1：按照列收集
# [0,0]：t[0, index[0,0]] = t[0, 0] = 1
# [0,1]：t[0, index[0,1]] = t[0, 0] = 1
# [1,0]：t[1, index[1,0]] = t[1, 1] = 4
# [1,1]：t[1, index[1,1]] = t[1, 0] = 3
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 2],
        [3, 4]])


tensor([[1, 1],
        [4, 3]])

In [6]:
# reshape改变张量的形状（不改变实际内容）
a = torch.arange(6)
torch.reshape(a, (2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])

In [7]:
torch.reshape(a, (3,2))

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
# reshape变成一维
torch.reshape(a, (-1,))

tensor([0, 1, 2, 3, 4, 5])

In [9]:
# 类似 gather，一个，但是会写入数据
src = torch.zeros((2,2), dtype=torch.float32)
dest = torch.arange(4, dtype=torch.float32).reshape((2,2))
print(dest)
dest.scatter(1, index=torch.tensor([[0, 0], [1, 0]]), src=src)

tensor([[0., 1.],
        [2., 3.]])


tensor([[0., 1.],
        [0., 0.]])

In [10]:
# 和chunk不同，split指定大小，chunk指定划分多少个
a = torch.arange(10).reshape((5,2))
a.split(2, dim=0)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [11]:
# split可以指定分成几分
a = torch.arange(12).reshape((-1,))
a.split([4,3,3,1,1], dim=0)

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6]),
 tensor([7, 8, 9]),
 tensor([10]),
 tensor([11]))

In [12]:
# squeeze对多余的维度压缩
a = torch.arange(12).reshape((1,2,3,2,1))
print(a, a.shape)
a.squeeze_()
print(a, a.shape)


tensor([[[[[ 0],
           [ 1]],

          [[ 2],
           [ 3]],

          [[ 4],
           [ 5]]],


         [[[ 6],
           [ 7]],

          [[ 8],
           [ 9]],

          [[10],
           [11]]]]]) torch.Size([1, 2, 3, 2, 1])
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]) torch.Size([2, 3, 2])


In [13]:
# squeeze 指定维度
a = torch.arange(12).reshape((1,2,3,2,1))
a.squeeze_(dim=0)
print(a.shape)

torch.Size([2, 3, 2, 1])


In [14]:
# stack：沿着新维度拼接起来
a = torch.ones((3,2))
b = torch.ones((3,2)) * 2
torch.stack([a,b]) # 变成3维 (2,3,2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.],
         [2., 2.]]])

In [15]:
torch.stack([a,b], dim=1) # 变成3维 (3,2,2)

tensor([[[1., 1.],
         [2., 2.]],

        [[1., 1.],
         [2., 2.]],

        [[1., 1.],
         [2., 2.]]])