# [3、PyTorch张量的运算API（下）](https://www.bilibili.com/video/BV1Hq4y1R7dM?spm_id_from=333.788.player.switch&vd_source=cdd897fffb54b70b076681c3c4e4d45d)

In [1]:
import torch

## [torch.dtype](https://docs.pytorch.org/docs/stable/tensor_attributes.html)

### 浮点数表示

注意 float16 指数5位，而bf16 指数占8位就好了。bf16指数位和32位的一样大但是精度不同

In [3]:
# transpose
a = torch.arange(4).reshape((2,2))
a.transpose(0, 1)

tensor([[0, 2],
        [1, 3]])

In [6]:
# take
a = torch.tensor([[4,3], [2,1]])
torch.take(a, torch.tensor([0,1,3]))

tensor([4, 3, 1])

In [16]:
# tile 复制
x = torch.tensor([1,2,3])
x.tile((2,)) # 对dim=0拷贝2份

tensor([1, 2, 3, 1, 2, 3])

In [ ]:
x = torch.tensor([[1,2], [3,4]])
x.tile((1,3)) # 对dim=1 拷贝3份

tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])

In [17]:
# 交换维度
a = torch.arange(6).reshape((2,3))
print(a)
a.transpose(0, 1) # 交换第 0,1 维度

tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [20]:
# unbind：移除张量的维度，返回所有此维度的元组
a = torch.arange(6).reshape((2,3))
print(a)
print(a.unbind(0))
print(a.unbind(1))

tensor([[0, 1, 2],
        [3, 4, 5]])
(tensor([0, 1, 2]), tensor([3, 4, 5]))
(tensor([0, 3]), tensor([1, 4]), tensor([2, 5]))


In [26]:
# unsqueeze：新增一个维度(expand_dims)
x = torch.tensor([1,2,3,4])
print(x, x.shape)
y = x.unsqueeze(0)
print(y, y.shape)
y = x.unsqueeze(1)
print(y, y.shape)

tensor([1, 2, 3, 4]) torch.Size([4])
tensor([[1, 2, 3, 4]]) torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]]) torch.Size([4, 1])


In [29]:
# where：根据条件返回 x 或者 y
t = torch.randn(3,2)
print(t)
x = torch.ones_like(t)
y = torch.zeros(1,2)
torch.where(t > 0, x, y) # xy可以广播

tensor([[-1.4589, -0.2763],
        [ 0.9700,  0.5336],
        [-0.1716, -1.1861]])


tensor([[0., 0.],
        [1., 1.],
        [0., 0.]])

In [ ]:
# manual_seed：指定随机种子，用于模型复现
torch.manual_seed(42)
print(torch.rand(2,3))
# 如果使用cuda,那么会对GPU也设置好随机数
# 注意使用numpy也需要设置随机种子

## 随机分布

In [ ]:
# 伯努利分布
# 将概率放入伯努利分布采样，返回 01
torch.bernoulli(
    torch.empty(3,3).uniform_(0, 1)
)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 0., 1.]])

In [ ]:
# 高斯分布，可以指定均值和标准差
torch.normal(
    mean=torch.zeros(2,3), std=torch.arange(6).reshape(2,3)
)

tensor([[ 0.0000,  0.8063, -2.0934],
        [-5.6108,  4.9884,  1.5667]])

In [ ]:
# rand：从 [0-1) 区间的均匀分布
# randn 从 [0-1) 区间的高斯分布
# randperm：获得随机组合
print(torch.rand(2,3))
print(torch.randn(2,3))
print(torch.randint(1,5, (3,)))
print(torch.randperm(4)) # 一般用于构建数据集

tensor([[0.2246, 0.9354, 0.3367],
        [0.9177, 0.8836, 0.6692]])
tensor([[-1.8539, -1.1582,  0.2880],
        [-0.8297, -0.0941,  1.4635]])
tensor([3, 3, 4])
tensor([0, 2, 3, 1])
